### PR TITLE
Run fireblock-tests on CI

### PR DESCRIPTION
**Pull request by TomasArrachea**

### CODE REVIEW

**Comment by supernovahs** [comment]
@TomasArrachea  the fireblock was tested using a free plan which has expired, we need a paid key ,and modify the test parameters according to it

**Comment by TomasArrachea** [comment]
> should we open this again @TomasArrachea ?

Yes, I think so. Im trying to run the tests locally and i still get the error "FIREBLOCKS_API_KEY not set", how should we run it?

**Comment by supernovahs** [comment]
I have the api key and secret key . I can share it with you.
adding these env vars in github  also today for ci

**Comment by supernovahs** [comment]
looks like fireblock test ci is running integration tests also

**Comment by supernovahs** [comment]
anup said he has added the keys on `testing` environment

**Pull request closed without merging**
